/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.Controlador;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;

import javax.swing.text.MaskFormatter;

/**
 *
 * @author user
 */
public class frmAdmFunciones extends javax.swing.JFrame {

    /**
     * Creates new form frmCaliPelicula
     */
    private Controlador cntl;
    private int pelicula;
    public frmAdmFunciones(Controlador c) {
        initComponents();
        this.cntl=c;
        this.setTitle("Cine Jungla");
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.jLabel4.setVisible(false);
        this.btnContinuar.setEnabled(false);
        this.setLista();
    }
    

    public void setLista(){
        DefaultComboBoxModel<String> model=null;
        String[] lista=cntl.getSalas();
        model= new DefaultComboBoxModel<>(lista);
        this.boxMultiplex.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnBatman = new javax.swing.JButton();
        btnUncharted = new javax.swing.JButton();
        btnMorbius = new javax.swing.JButton();
        btnSonic = new javax.swing.JButton();
        btnEncanto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        try {
            MaskFormatter formatter = new MaskFormatter("##/##/##");
            txtFechaAdm = new javax.swing.JFormattedTextField(formatter);
            jLabel4 = new javax.swing.JLabel();
            MaskFormatter format=new MaskFormatter("##:##");
            jtxthora = new javax.swing.JFormattedTextField(format);
            jLabel5 = new javax.swing.JLabel();
            boxMultiplex = new javax.swing.JComboBox<>();
            jLabel6 = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jPanel1.setBackground(new java.awt.Color(253, 255, 244));
            jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            btnBatman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Batman.png"))); // NOI18N
            btnBatman.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnBatmanActionPerformed(evt);
                }
            });
            jPanel1.add(btnBatman, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 240, 330));

            btnUncharted.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Uncharted.jpg"))); // NOI18N
            btnUncharted.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnUnchartedActionPerformed(evt);
                }
            });
            jPanel1.add(btnUncharted, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 100, 240, 330));

            btnMorbius.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Morbius.jpg"))); // NOI18N
            btnMorbius.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnMorbiusActionPerformed(evt);
                }
            });
            jPanel1.add(btnMorbius, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 240, 330));

            btnSonic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sonic.jpg"))); // NOI18N
            btnSonic.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnSonicActionPerformed(evt);
                }
            });
            jPanel1.add(btnSonic, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 240, 330));

            btnEncanto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Encanto.jpg"))); // NOI18N
            btnEncanto.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnEncantoActionPerformed(evt);
                }
            });
            jPanel1.add(btnEncanto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 100, 240, 330));

            jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText("Calificación");
            jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 260, 70));

            btnContinuar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            btnContinuar.setText("Añadir");
            btnContinuar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnContinuarActionPerformed(evt);
                }
            });
            jPanel1.add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 510, 150, 50));

            jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            jLabel2.setText("Añadir Fecha (Año-Mes-dia)");
            jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, -1, -1));

        } catch (ParseException ex) {
            Logger.getLogger(frmAdmFunciones.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtFechaAdm.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        txtFechaAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaAdmActionPerformed(evt);
            }
        });
        jPanel1.add(txtFechaAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, 210, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Ingrese valores validos en la fecha y hora");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 600, -1, -1));

        jtxthora.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jtxthora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxthoraActionPerformed(evt);
            }
        });
        jPanel1.add(jtxthora, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, 210, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Añadir Hora (Hora:Minuto)");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 570, -1, -1));

        boxMultiplex.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        boxMultiplex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Titán", "Unicentro", "Plaza Central", "Gran Estación", "Embajador (centro)", "Las Américas" }));
        boxMultiplex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxMultiplexActionPerformed(evt);
            }
        });
        jPanel1.add(boxMultiplex, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 630, 130, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Sala en la que se presentara:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 640, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1299, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncantoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncantoActionPerformed
        btnBatman.setEnabled(true);
        btnUncharted.setEnabled(true);
        btnEncanto.setEnabled(false);
        btnMorbius.setEnabled(true);
        btnSonic.setEnabled(true);
        this.btnContinuar.setEnabled(true);
        this.pelicula=4;
    }//GEN-LAST:event_btnEncantoActionPerformed

    private void btnSonicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSonicActionPerformed
        btnBatman.setEnabled(true);
        btnUncharted.setEnabled(true);
        btnEncanto.setEnabled(true);
        btnMorbius.setEnabled(true);
        btnSonic.setEnabled(false);
        this.btnContinuar.setEnabled(true);
        this.pelicula=3;
    }//GEN-LAST:event_btnSonicActionPerformed

    private void btnMorbiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMorbiusActionPerformed
        btnBatman.setEnabled(true);
        btnUncharted.setEnabled(true);
        btnEncanto.setEnabled(true);
        btnMorbius.setEnabled(false);
        btnSonic.setEnabled(true);
        this.btnContinuar.setEnabled(true);
        this.pelicula=2;
    }//GEN-LAST:event_btnMorbiusActionPerformed

    private void btnUnchartedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnchartedActionPerformed
        btnBatman.setEnabled(true);
        btnUncharted.setEnabled(false);
        btnEncanto.setEnabled(true);
        btnMorbius.setEnabled(true);
        btnSonic.setEnabled(true);
        this.btnContinuar.setEnabled(true);
        this.pelicula=1;
    }//GEN-LAST:event_btnUnchartedActionPerformed

    private void btnBatmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatmanActionPerformed
        btnBatman.setEnabled(false);
        btnUncharted.setEnabled(true);
        btnEncanto.setEnabled(true);
        btnMorbius.setEnabled(true);
        btnSonic.setEnabled(true);
        this.btnContinuar.setEnabled(true);
        this.pelicula=0;
    }//GEN-LAST:event_btnBatmanActionPerformed

    private void txtFechaAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaAdmActionPerformed

    private void jtxthoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxthoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxthoraActionPerformed

    private void boxMultiplexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxMultiplexActionPerformed
        DefaultComboBoxModel<String> model=null;
        String multi=String.valueOf(this.boxMultiplex.getSelectedItem());
    }//GEN-LAST:event_boxMultiplexActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // TODO add your handling code here:
        String fecha=(String) this.txtFechaAdm.getValue();
        String hora =(String) this.jtxthora.getValue();
        Date fechafinal=null;
        SimpleDateFormat format=new SimpleDateFormat("yyyy/MM/dd HH:mm");
        String fecha1="20"+fecha+" "+hora;
        System.out.println("la fecha es: " +fecha1);

        if(Integer.parseInt((String) fecha.subSequence(3,5))>12){
            this.jLabel4.setText("ingrese un valor valido en la fecha");
            this.jLabel4.setVisible(true);
        }else if(Integer.parseInt((String) fecha.subSequence(6,8))>30){
            this.jLabel4.setText("ingrese un valor valido en la fecha");
            this.jLabel4.setVisible(true);
        }else if(Integer.parseInt((String) fecha.subSequence(0,2))<21){
            this.jLabel4.setText("ingrese un valor valido en la fecha");
            this.jLabel4.setVisible(true);
        }else if(Integer.parseInt((String) hora.subSequence(0,2))>24){
            this.jLabel4.setText("ingrese un valor valido en la hora");
            this.jLabel4.setVisible(true);
        }else if(Integer.parseInt((String) hora.subSequence(3,5))>60){
            this.jLabel4.setText("ingrese un valor valido en la hora");
            this.jLabel4.setVisible(true);
        }else{
            this.jLabel4.setVisible(false);
            try {
                fechafinal=format.parse(fecha1);
            } catch (ParseException ex) {
                Logger.getLogger(frmAdmFunciones.class.getName()).log(Level.SEVERE, null, ex);
                return;
            }
            if(this.boxMultiplex.getSelectedIndex()==0){
                this.jLabel4.setText("escoja una de las salas");
                this.jLabel4.setVisible(true);
            }else{
                cntl.addFuncion(fechafinal,this.boxMultiplex.getSelectedIndex(),
                        pelicula);
                this.dispose();
                cntl.admin("funcion");
            }
        } 
        
    }//GEN-LAST:event_btnContinuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxMultiplex;
    private javax.swing.JButton btnBatman;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnEncanto;
    private javax.swing.JButton btnMorbius;
    private javax.swing.JButton btnSonic;
    private javax.swing.JButton btnUncharted;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField jtxthora;
    private javax.swing.JFormattedTextField txtFechaAdm;
    // End of variables declaration//GEN-END:variables
}
