/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.Controlador;
import javax.swing.JButton;
import javax.swing.JMenuItem;
import javax.swing.JTable;

/**
 *
 * @author user
 */
public class frmAdmin extends javax.swing.JFrame {

    /**
     * Creates new form frmAdmin
     */
    Controlador cntl;
    public frmAdmin(Controlador c,String origen) {
        initComponents();
        this.cntl=c;
        this.setTitle("Cine Jungla");
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        System.out.println(cntl.getCargo());
        this.origen.setVisible(false);
        this.multi.setText("multiplex  "+ cntl.getMulti());
        if(origen.equals("funcion")){
            this.origen.setVisible(true);
        }
        this.btnModificar.setVisible(false);
        if(cntl.getCargo().equals("director")){
            System.out.println(cntl.getCargo());
            this.btnEliminar.setVisible(true);
            this.btnAgregar.setVisible(true);
            this.btnModificar.setVisible(true);
            this.btnVendBoletos.setEnabled(false);
            this.btnAdmFunciones.setEnabled(false);
            this.setTabla();
        }else if(cntl.getCargo().equals("cajero")){
            this.btnVendSnacks.setEnabled(false);
            this.btnEliminar.setVisible(false);
            this.btnAgregar.setVisible(false);
            this.btnModificar.setVisible(false);
            this.setTabla();
        }else if(cntl.getCargo().equals("despachador de comida")){
            this.btnEliminar.setVisible(false);
            this.btnAgregar.setVisible(false);
            this.btnModificar.setVisible(false);
            this.btnVendBoletos.setEnabled(false);
            this.btnAdmFunciones.setEnabled(false);
            this.setTabla();
        }else{
            this.btnEliminar.setVisible(false);
            this.btnAgregar.setVisible(false);
            this.btnModificar.setVisible(false);
            this.btnVendSnacks.setEnabled(false);
            this.btnVendBoletos.setEnabled(false);
            this.btnAdmFunciones.setEnabled(false);
            this.setTabla();
        }
    }
    
    public void setTabla(){
        this.tbEmpleados.setValueAt(this.cntl.getCodAdmin(), 0, 0);
        this.tbEmpleados.setValueAt(this.cntl.getCedula(), 0, 1);
        this.tbEmpleados.setValueAt(this.cntl.getAdNombre(), 0, 2);
        this.tbEmpleados.setValueAt(this.cntl.getTel(), 0, 3);
        this.tbEmpleados.setValueAt(this.cntl.getFecha(), 0, 4);
        this.tbEmpleados.setValueAt(this.cntl.getSalario(), 0, 5);
        this.tbEmpleados.setValueAt(this.cntl.getCargo(), 0, 6);
    }

    public JButton getBtnAdmFunciones() {
        return btnAdmFunciones;
    }

    public void setBtnAdmFunciones(JButton btnAdmFunciones) {
        this.btnAdmFunciones = btnAdmFunciones;
    }

    public JButton getBtnVendBoletos() {
        return btnVendBoletos;
    }

    public void setBtnVendBoletos(JButton btnVendBoletos) {
        this.btnVendBoletos = btnVendBoletos;
    }

    public JButton getBtnVendSnacks() {
        return btnVendSnacks;
    }

    public void setBtnVendSnacks(JButton btnVendSnacks) {
        this.btnVendSnacks = btnVendSnacks;
    }

    public JMenuItem getMenuReporte() {
        return menuReporte;
    }

    public void setMenuReporte(JMenuItem menuReporte) {
        this.menuReporte = menuReporte;
    }

    public JMenuItem getMenuClose() {
        return menuClose;
    }

    public void setMenuClose(JMenuItem menuClose) {
        this.menuClose = menuClose;
    }

    public JButton getBtnAgregar() {
        return btnAgregar;
    }

    public void setBtnAgregar(JButton btnAgregar) {
        this.btnAgregar = btnAgregar;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public void setBtnEliminar(JButton btnEliminar) {
        this.btnEliminar = btnEliminar;
    }

    public JButton getBtnModificar() {
        return btnModificar;
    }

    public void setBtnModificar(JButton btnModificar) {
        this.btnModificar = btnModificar;
    }

    public JTable getTbEmpleados() {
        return tbEmpleados;
    }

    public void setTbEmpleados(JTable tbEmpleados) {
        this.tbEmpleados = tbEmpleados;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEmpleados = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnAdmFunciones = new javax.swing.JButton();
        btnVendBoletos = new javax.swing.JButton();
        btnVendSnacks = new javax.swing.JButton();
        multi = new javax.swing.JLabel();
        origen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuClose = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuReporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(34, 177, 76));

        jPanel1.setBackground(new java.awt.Color(253, 255, 244));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Administración");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        tbEmpleados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Cedula", "Nombre", "Telefono", "Inicio Contrato", "Salario", "Cargo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Long.class, java.lang.String.class, java.lang.Long.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbEmpleados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 1070, 130));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Lista de Empleados");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 370, 120, 60));

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 290, 120, 60));

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 450, 120, 60));

        btnAdmFunciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdmFunciones.setText("Administrar Funciones");
        btnAdmFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmFuncionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdmFunciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 190, 50));

        btnVendBoletos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVendBoletos.setText("Vender Boletos");
        btnVendBoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendBoletosActionPerformed(evt);
            }
        });
        jPanel1.add(btnVendBoletos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 140, 50));

        btnVendSnacks.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVendSnacks.setText("vender Snacks");
        btnVendSnacks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendSnacksActionPerformed(evt);
            }
        });
        jPanel1.add(btnVendSnacks, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 140, 50));

        multi.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        multi.setText("Multiplex");
        jPanel1.add(multi, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 230, 30));

        origen.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        origen.setText("Se añadido la función satisfactoriamente");
        jPanel1.add(origen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 330, -1));

        jMenu1.setText("Ajustes");

        menuClose.setText("Cerrar Sesión");
        menuClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCloseActionPerformed(evt);
            }
        });
        jMenu1.add(menuClose);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reportes");

        menuReporte.setText("Reporte Mensual");
        jMenu2.add(menuReporte);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1299, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void menuCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
        cntl.setEmpleado(null);
        cntl.newPeli();
    }//GEN-LAST:event_menuCloseActionPerformed

    private void btnVendBoletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendBoletosActionPerformed
        // TODO add your handling code here:
        this.dispose();
        cntl.newPeli();
    }//GEN-LAST:event_btnVendBoletosActionPerformed

    private void btnVendSnacksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendSnacksActionPerformed
        // TODO add your handling code here:
        this.dispose();
        cntl.snacks();
    }//GEN-LAST:event_btnVendSnacksActionPerformed

    private void btnAdmFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmFuncionesActionPerformed
        // TODO add your handling code here:
        this.dispose();
        cntl.addFun();
    }//GEN-LAST:event_btnAdmFuncionesActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        cntl.resEmpl();
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmFunciones;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVendBoletos;
    private javax.swing.JButton btnVendSnacks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuClose;
    private javax.swing.JMenuItem menuReporte;
    private javax.swing.JLabel multi;
    private javax.swing.JLabel origen;
    private javax.swing.JTable tbEmpleados;
    // End of variables declaration//GEN-END:variables
}
