/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.Controlador;
import Logica.Persona;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JMenuItem;

/**
 *
 * @author user
 */
public class frmCliente extends javax.swing.JFrame {

    /**
     * Creates new form frmPeliculas
     */
    private Controlador cntl;
    private int movie;
    private String estado;
    
    public frmCliente(Controlador c) {
        this.initComponents();
        this.setTitle("Cine Jungla");
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
        this.cntl=c;
        this.nombre.setVisible(false);
        this.cntl.getpeliculas();
        this.estado="inicio";
        if(cntl.getPer()!=null){
            this.init();
        }else if(cntl.getEm()!=null){
            this.init2();
        }
    }

    public void init(){
        this.btnInicioSesion.setText("cerrar sesion");
        this.btnCalifPel.setEnabled(true);
        this.nombre.setText("Bienvenido  "+cntl.getNombre());
        this.nombre.setVisible(true);
        this.estado="usuario";
    }
    
    public void init2(){
        this.btnInicioSesion.setText("cerrar sesion");
        this.nombre.setText("Bienvenido  "+cntl.getAdNombre());
        this.nombre.setVisible(true);
        this.estado="admin";
    }
    
    public void setLista(){
        DefaultComboBoxModel<String> model=null;
        String multi=String.valueOf(this.boxMultiplex.getSelectedItem());
        String[] lista=cntl.getFunciones(this.movie,multi);
        model= new DefaultComboBoxModel<>(lista);
        this.boxHora.setModel(model);
        this.boxHora.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnBatman = new javax.swing.JButton();
        btnUncharted = new javax.swing.JButton();
        btnMorbius = new javax.swing.JButton();
        btnSonic = new javax.swing.JButton();
        btnEncanto = new javax.swing.JButton();
        boxMultiplex = new javax.swing.JComboBox<>();
        boxHora = new javax.swing.JComboBox<>();
        btnAceptar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblDescrip = new javax.swing.JLabel();
        btnCalifPel = new javax.swing.JButton();
        btnInicioSesion = new javax.swing.JButton();
        nombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        boxMultiplex1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(34, 140, 85));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBatman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Batman.png"))); // NOI18N
        btnBatman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatmanActionPerformed(evt);
            }
        });
        jPanel2.add(btnBatman, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 240, 330));

        btnUncharted.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Uncharted.jpg"))); // NOI18N
        btnUncharted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnchartedActionPerformed(evt);
            }
        });
        jPanel2.add(btnUncharted, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 100, 240, 330));

        btnMorbius.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Morbius.jpg"))); // NOI18N
        btnMorbius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMorbiusActionPerformed(evt);
            }
        });
        jPanel2.add(btnMorbius, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 240, 330));

        btnSonic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sonic.jpg"))); // NOI18N
        btnSonic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSonicActionPerformed(evt);
            }
        });
        jPanel2.add(btnSonic, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 240, 330));

        btnEncanto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Encanto.jpg"))); // NOI18N
        btnEncanto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncantoActionPerformed(evt);
            }
        });
        jPanel2.add(btnEncanto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 100, 240, 330));

        boxMultiplex.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        boxMultiplex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Titán", "Unicentro", "Plaza Central", "Gran Estación", "Embajador (centro)", "Las Américas" }));
        boxMultiplex.setEnabled(false);
        boxMultiplex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxMultiplexActionPerformed(evt);
            }
        });
        jPanel2.add(boxMultiplex, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, 130, 40));

        boxHora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        boxHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "10:00 am", "01:00 pm", "04:00 pm", "07:00 pm", "10:00 pm" }));
        boxHora.setEnabled(false);
        boxHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxHoraActionPerformed(evt);
            }
        });
        jPanel2.add(boxHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 570, 190, 40));

        btnAceptar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setEnabled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 510, 210, 50));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 250, 40));

        lblDescrip.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDescrip.setToolTipText("");
        lblDescrip.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(lblDescrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 430, 180));

        btnCalifPel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalifPel.setText("Calificar Peliculas");
        btnCalifPel.setEnabled(false);
        btnCalifPel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalifPelActionPerformed(evt);
            }
        });
        jPanel2.add(btnCalifPel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 140, 40));

        btnInicioSesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInicioSesion.setText("Iniciar Sesión");
        btnInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSesionActionPerformed(evt);
            }
        });
        jPanel2.add(btnInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 20, 140, 40));

        nombre.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        nombre.setText("Bienvenido ");
        jPanel2.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 70, 140, -1));

        jLabel1.setFont(new java.awt.Font("Milky Nice", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo3.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        boxMultiplex1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        boxMultiplex1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Titán", "Unicentro", "Plaza Central", "Gran Estación", "Embajador (centro)", "Las Américas" }));
        boxMultiplex1.setEnabled(false);
        boxMultiplex1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxMultiplex1ActionPerformed(evt);
            }
        });
        jPanel2.add(boxMultiplex1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatmanActionPerformed
        
        btnBatman.setEnabled(false);
        btnUncharted.setEnabled(true);
        btnEncanto.setEnabled(true);
        btnMorbius.setEnabled(true);
        btnSonic.setEnabled(true);
        movie=1;
        
        boxMultiplex.setEnabled(true);
        boxMultiplex.setSelectedIndex(0);
        boxHora.setEnabled(false);
        boxHora.setSelectedIndex(0);
        if(cntl.getEm()!=null){
            this.boxMultiplex.setSelectedIndex((this.cntl.getIdMult()));
            this.boxMultiplex.setEnabled(false);
            this.setLista();
        }
        lblTitulo.setText(cntl.getPeliNombre(0));
        lblDescrip.setText("<html>"+cntl.getPeliSinop(0)+"<br>Duracion: "
            +cntl.getPeliDur(0)+"<br>Generos: "+cntl.getPeliGenero(0)+"<html>");
    }//GEN-LAST:event_btnBatmanActionPerformed

    private void btnUnchartedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnchartedActionPerformed
        btnBatman.setEnabled(true);
        btnUncharted.setEnabled(false);
        btnEncanto.setEnabled(true);
        btnMorbius.setEnabled(true);
        btnSonic.setEnabled(true);
        movie=2;
        
        boxMultiplex.setEnabled(true);
        boxMultiplex.setSelectedIndex(0);
        boxHora.setEnabled(false);
        boxHora.setSelectedIndex(0);
        if(cntl.getEm()!=null){
            this.boxMultiplex.setSelectedIndex((this.cntl.getIdMult()));
            this.boxMultiplex.setEnabled(false);
            this.setLista();
        }
        lblTitulo.setText(cntl.getPeliNombre(1));
        lblDescrip.setText("<html>"+cntl.getPeliSinop(1)+"<br>Duracion: "
            +cntl.getPeliDur(1)+" minutos<br>Generos: "
                +cntl.getPeliGenero(1)+"<html>");
    }//GEN-LAST:event_btnUnchartedActionPerformed

    private void btnMorbiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMorbiusActionPerformed
        btnBatman.setEnabled(true);
        btnUncharted.setEnabled(true);
        btnEncanto.setEnabled(true);
        btnMorbius.setEnabled(false);
        btnSonic.setEnabled(true);
        movie=3;
        
        boxMultiplex.setEnabled(true);
        boxMultiplex.setSelectedIndex(0);
        boxHora.setEnabled(false);
        boxHora.setSelectedIndex(0);
        if(cntl.getEm()!=null){
            this.boxMultiplex.setSelectedIndex((this.cntl.getIdMult()));
            this.boxMultiplex.setEnabled(false);
            this.setLista();
        }
        lblTitulo.setText(cntl.getPeliNombre(2));
        lblDescrip.setText("<html>"+cntl.getPeliSinop(2)+"<br>Duracion: "
            +cntl.getPeliDur(2)+" minutos<br>Generos: "
                +cntl.getPeliGenero(2)+"<html>");
    }//GEN-LAST:event_btnMorbiusActionPerformed

    private void btnSonicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSonicActionPerformed
        btnBatman.setEnabled(true);
        btnUncharted.setEnabled(true);
        btnEncanto.setEnabled(true);
        btnMorbius.setEnabled(true);
        btnSonic.setEnabled(false);
        movie=4;
        
        boxMultiplex.setEnabled(true);
        boxMultiplex.setSelectedIndex(0);
        boxHora.setEnabled(false);
        boxHora.setSelectedIndex(0);
        if(cntl.getEm()!=null){
            this.boxMultiplex.setSelectedIndex((this.cntl.getIdMult()));
            this.boxMultiplex.setEnabled(false);
            this.setLista();
        }
        lblTitulo.setText(cntl.getPeliNombre(0));
        lblDescrip.setText("<html>"+cntl.getPeliSinop(3)+"<br>Duracion: "
            +cntl.getPeliDur(3)+" minutos<br>Generos: "
                +cntl.getPeliGenero(3)+"<html>");
    }//GEN-LAST:event_btnSonicActionPerformed

    private void btnEncantoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncantoActionPerformed
        btnBatman.setEnabled(true);
        btnUncharted.setEnabled(true);
        btnEncanto.setEnabled(false);
        btnMorbius.setEnabled(true);
        btnSonic.setEnabled(true);
        movie=5;
        
        boxMultiplex.setEnabled(true);
        boxMultiplex.setSelectedIndex(0);
        boxHora.setEnabled(false);
        boxHora.setSelectedIndex(0);
        if(cntl.getEm()!=null){
            this.boxMultiplex.setSelectedIndex((this.cntl.getIdMult()));
            this.boxMultiplex.setEnabled(false);
            this.setLista();
        }
        lblTitulo.setText(cntl.getPeliNombre(4));
        lblDescrip.setText("<html>"+cntl.getPeliSinop(4)+"<br>Duracion: "
            +cntl.getPeliDur(4)+" minutos<br>Generos: "
                +cntl.getPeliGenero(4)+"<html>");
    }//GEN-LAST:event_btnEncantoActionPerformed

    private void boxMultiplexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxMultiplexActionPerformed
        this.setLista();
    }//GEN-LAST:event_boxMultiplexActionPerformed

    private void boxHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxHoraActionPerformed
        if(this.boxHora.getSelectedIndex()!=0){
            this.btnAceptar.setEnabled(true);
        }else{
            this.btnAceptar.setEnabled(false);
        }
    }//GEN-LAST:event_boxHoraActionPerformed

    private void btnInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSesionActionPerformed
        // TODO add your handling code here:
        if(this.cntl.getPer()==null&this.cntl.getEm()==null){
            this.dispose();
            this.cntl.initSesion();
        } else{
            this.dispose();
            this.cntl.setPer(null);
            this.cntl.setEmpleado(null);
            this.cntl.newPeli();
        }
    }//GEN-LAST:event_btnInicioSesionActionPerformed

    private void btnCalifPelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalifPelActionPerformed
        // TODO add your handling code here:
        this.dispose();
        cntl.calPeli();
    }//GEN-LAST:event_btnCalifPelActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.cntl.setFuncion(this.boxHora.getSelectedIndex(),this.movie);
        if(this.cntl.getEm()==null&this.cntl.getPer()==null){
            this.cntl.initSesion();
        }else{
            System.out.println("entro");
            this.cntl.selectSilla();
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void boxMultiplex1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxMultiplex1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxMultiplex1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxHora;
    private javax.swing.JComboBox<String> boxMultiplex;
    private javax.swing.JComboBox<String> boxMultiplex1;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBatman;
    private javax.swing.JButton btnCalifPel;
    private javax.swing.JButton btnEncanto;
    private javax.swing.JButton btnInicioSesion;
    private javax.swing.JButton btnMorbius;
    private javax.swing.JButton btnSonic;
    private javax.swing.JButton btnUncharted;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDescrip;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
