/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.Controlador;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JToggleButton;

/**
 *
 * @author user
 */
public class frmFinal extends javax.swing.JFrame {
    
    private Controlador cntl;
    private int nota;

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public void setButtonGroup1(ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    /**
     * Creates new form frmCalificacion
     */
    public frmFinal(Controlador c) {
        initComponents();
        cntl=c;
        this.setTitle("Cine Jungla");
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setFactura();
        this.ver.setVisible(false);
        this.error.setVisible(false);
        if(this.cntl.getEm()==null){
            this.puntos.setVisible(false);
            this.ver.setVisible(false);
            this.jButton1.setVisible(false);
            this.disponibles.setVisible(false);
            this.docs.setVisible(false);
            this.cod.setVisible(false);
            this.verif.setVisible(false);
        }
        
    }
    
    public void setFactura(){
        this.txtFactura.setText(cntl.getBoletos());
        if(cntl.getPer()!=null){
            this.puntos.setText(String.valueOf(cntl.getPuntos()));
        }else{
            this.puntos.setText("no se ha registrado ningun usuario");
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFactura = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        Estrella5 = new javax.swing.JToggleButton();
        Estrella1 = new javax.swing.JToggleButton();
        Estrella2 = new javax.swing.JToggleButton();
        Estrella3 = new javax.swing.JToggleButton();
        Estrella4 = new javax.swing.JToggleButton();
        btnFinalizar = new javax.swing.JButton();
        ver = new javax.swing.JLabel();
        puntos = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        disponibles = new javax.swing.JLabel();
        docs = new javax.swing.JLabel();
        cod = new javax.swing.JTextField();
        verif = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuClose = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(253, 255, 244));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Resumen de la Compra");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        txtFactura.setColumns(20);
        txtFactura.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFactura.setRows(5);
        txtFactura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFactura.setEnabled(false);
        jPanel1.add(txtFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 640, 190));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Califique nuestro servicio:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        buttonGroup1.add(Estrella5);
        Estrella5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Estrella5.png"))); // NOI18N
        Estrella5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Estrella5ActionPerformed(evt);
            }
        });
        jPanel1.add(Estrella5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 80, 80));

        buttonGroup1.add(Estrella1);
        Estrella1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Estrella1.png"))); // NOI18N
        Estrella1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Estrella1ActionPerformed(evt);
            }
        });
        jPanel1.add(Estrella1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 80, 80));

        buttonGroup1.add(Estrella2);
        Estrella2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Estrella2.png"))); // NOI18N
        Estrella2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Estrella2ActionPerformed(evt);
            }
        });
        jPanel1.add(Estrella2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 80, 80));

        buttonGroup1.add(Estrella3);
        Estrella3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Estrella3.png"))); // NOI18N
        Estrella3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Estrella3ActionPerformed(evt);
            }
        });
        jPanel1.add(Estrella3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 80, 80));

        buttonGroup1.add(Estrella4);
        Estrella4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Estrella4.png"))); // NOI18N
        Estrella4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Estrella4ActionPerformed(evt);
            }
        });
        jPanel1.add(Estrella4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 80, 80));

        btnFinalizar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFinalizar.setText("Finalizar Transacción");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 300, 60));

        ver.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        ver.setText("Se redimieron sus puntos por boletas");
        jPanel1.add(ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 220, 30));

        puntos.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        puntos.setText("0");
        jPanel1.add(puntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 330, 30, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jButton1.setText("Redimir por boletas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, -1, -1));

        disponibles.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        disponibles.setText("Puntos disponibles");
        jPanel1.add(disponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 150, -1));

        docs.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        docs.setText("Documento del usuario");
        jPanel1.add(docs, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 150, -1));

        cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codActionPerformed(evt);
            }
        });
        jPanel1.add(cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 90, 30));

        verif.setText("Verificar");
        verif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifActionPerformed(evt);
            }
        });
        jPanel1.add(verif, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, -1, -1));

        error.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        error.setText("El documento no se encuentra registrado");
        jPanel1.add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 330, 40));

        jMenu1.setText("Ajustes");

        menuClose.setText("Cerrar Sesión");
        jMenu1.add(menuClose);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Estrella3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Estrella3ActionPerformed
        // TODO add your handling code here:
        this.nota=3;
    }//GEN-LAST:event_Estrella3ActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Gracias por su compra");
        this.dispose();
        if(this.nota!=0){
            cntl.calif(this.nota);
        }
        cntl.comprarBoletos();
        cntl.newPeli();
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(Integer.parseInt(this.puntos.getText())>100){
            this.ver.setVisible(true);
            cntl.redimir((int)Math.floor(Integer.parseInt(this.puntos.getText())/100));
        }else{
            this.ver.setText("no hay suficientes puntos");
            this.ver.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Estrella1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Estrella1ActionPerformed
        // TODO add your handling code here:
        this.nota=1;
    }//GEN-LAST:event_Estrella1ActionPerformed

    private void Estrella2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Estrella2ActionPerformed
        // TODO add your handling code here:
        this.nota=2;
    }//GEN-LAST:event_Estrella2ActionPerformed

    private void Estrella4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Estrella4ActionPerformed
        // TODO add your handling code here:
        this.nota=4;
        
    }//GEN-LAST:event_Estrella4ActionPerformed

    private void Estrella5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Estrella5ActionPerformed
        // TODO add your handling code here:
        this.nota=1;
    }//GEN-LAST:event_Estrella5ActionPerformed

    private void codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codActionPerformed

    private void verifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifActionPerformed
        // TODO add your handling code here:
        boolean confirm=cntl.getUsuario(Integer.parseInt(this.cod.getText()));
        if (confirm){
            this.error.setText("se ha conectado correctamente con el usuario");
            this.error.setVisible(true);
            this.puntos.setText(""+this.cntl.getPuntos());
        }else{
             this.error.setVisible(true);
        }
    }//GEN-LAST:event_verifActionPerformed

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Estrella1;
    private javax.swing.JToggleButton Estrella2;
    private javax.swing.JToggleButton Estrella3;
    private javax.swing.JToggleButton Estrella4;
    private javax.swing.JToggleButton Estrella5;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cod;
    private javax.swing.JLabel disponibles;
    private javax.swing.JLabel docs;
    private javax.swing.JLabel error;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuClose;
    private javax.swing.JLabel puntos;
    private javax.swing.JTextArea txtFactura;
    private javax.swing.JLabel ver;
    private javax.swing.JButton verif;
    // End of variables declaration//GEN-END:variables
}
