/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.Controlador;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class frmRegistroEmp extends javax.swing.JFrame {

    /**
     * Creates new form frmEncuesta
     */
    
    private Controlador cntl;
    public frmRegistroEmp(Controlador c) {
        initComponents();
        cntl=c;
        this.setTitle("Cine Jungla");
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        if(this.cntl.getPer()!=null){
            this.setUsuario();
        }
    }
    
    public void setUsuario(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCódigoE = new javax.swing.JTextField();
        txtCedulaE = new javax.swing.JTextField();
        txtNombreE = new javax.swing.JTextField();
        txtTelefonoE = new javax.swing.JTextField();
        txtInicioContrato = new javax.swing.JFormattedTextField();
        txtSalario = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        boxMultiplex = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtMovilidadE = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(253, 255, 244));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setText("Registro de Empleado");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Multiplex");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Código");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Cédula");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Nombre");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Teléfono");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("<html>Fecha de Inicio de Contrato<html>");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 170, 70));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Salario");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Cargo");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, -1));
        jPanel1.add(txtCódigoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 210, 40));
        jPanel1.add(txtCedulaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 210, 40));
        jPanel1.add(txtNombreE, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 210, 40));
        jPanel1.add(txtTelefonoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 210, 40));

        txtInicioContrato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jPanel1.add(txtInicioContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 210, 40));
        jPanel1.add(txtSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 210, 40));
        jPanel1.add(txtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 210, 40));

        boxMultiplex.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        boxMultiplex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Titán", "Unicentro", "Plaza Central", "Gran Estación", "Embajador (centro)", "Las Américas" }));
        boxMultiplex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxMultiplexActionPerformed(evt);
            }
        });
        jPanel1.add(boxMultiplex, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 210, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("<html>Registro de Movilidad (Multiplex Titan)<html>");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 200, 50));

        txtMovilidadE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        txtMovilidadE.setEnabled(false);
        jPanel1.add(txtMovilidadE, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 210, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxMultiplexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxMultiplexActionPerformed
        if(boxMultiplex.getSelectedIndex()==1){
            txtMovilidadE.setEnabled(true);
        }
    }//GEN-LAST:event_boxMultiplexActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxMultiplex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtCedulaE;
    private javax.swing.JTextField txtCódigoE;
    private javax.swing.JFormattedTextField txtInicioContrato;
    private javax.swing.JFormattedTextField txtMovilidadE;
    private javax.swing.JTextField txtNombreE;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtTelefonoE;
    // End of variables declaration//GEN-END:variables
}
