/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.Controlador;
import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author user
 */
public class frmSillas extends javax.swing.JFrame {
    
    Controlador cntl;
    JToggleButton[][] sillasPref;
    JToggleButton[][] sillasGener;
    public frmSillas(Controlador c) {
        initComponents();
        cntl=c;
        this.setTitle("Cine Jungla");
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
        this.setArreglos();
        this.error.setVisible(false);
    }

    public void setArreglos(){
        JToggleButton[][] sillasP = {{E1, E2, E3, E4, E5, E6, E7, E8, E9, E10}, 
                                    {F1, F2, F3, F4, F5, F6, F7, F8, F9, F10}};
        JToggleButton[][] sillasG={{A1, A2, A3, A4, A5, A6, A7, A8, A9, A10},
                                    {B1, B2, B3, B4, B5, B6, B7, B8, B9, B10},
                                    {C1, C2, C3, C4, C5, C6, C7, C8, C9, C10},
                                    {D1, D2, D3, D4, D5, D6, D7, D8, D9, D10}};
        this.sillasPref=sillasP;
        this.sillasGener=sillasG;
        
        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 10; j++) {
                this.sillasGener[i][j].setEnabled(false);
                
            }
        }
        
        for (int i = 0; i < 2; i++) {
            for (int j = 0; j < 10; j++) {
                sillasPref[i][j].setEnabled(false);
                
            }
        }
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupo = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        A1 = new javax.swing.JToggleButton();
        A2 = new javax.swing.JToggleButton();
        A3 = new javax.swing.JToggleButton();
        A4 = new javax.swing.JToggleButton();
        A5 = new javax.swing.JToggleButton();
        A6 = new javax.swing.JToggleButton();
        A7 = new javax.swing.JToggleButton();
        A8 = new javax.swing.JToggleButton();
        A9 = new javax.swing.JToggleButton();
        A10 = new javax.swing.JToggleButton();
        B1 = new javax.swing.JToggleButton();
        B2 = new javax.swing.JToggleButton();
        B3 = new javax.swing.JToggleButton();
        B4 = new javax.swing.JToggleButton();
        B5 = new javax.swing.JToggleButton();
        B6 = new javax.swing.JToggleButton();
        B7 = new javax.swing.JToggleButton();
        B8 = new javax.swing.JToggleButton();
        B9 = new javax.swing.JToggleButton();
        B10 = new javax.swing.JToggleButton();
        C1 = new javax.swing.JToggleButton();
        C2 = new javax.swing.JToggleButton();
        C3 = new javax.swing.JToggleButton();
        C4 = new javax.swing.JToggleButton();
        C5 = new javax.swing.JToggleButton();
        C6 = new javax.swing.JToggleButton();
        C7 = new javax.swing.JToggleButton();
        C8 = new javax.swing.JToggleButton();
        C9 = new javax.swing.JToggleButton();
        C10 = new javax.swing.JToggleButton();
        D1 = new javax.swing.JToggleButton();
        D2 = new javax.swing.JToggleButton();
        D3 = new javax.swing.JToggleButton();
        D4 = new javax.swing.JToggleButton();
        D5 = new javax.swing.JToggleButton();
        D6 = new javax.swing.JToggleButton();
        D7 = new javax.swing.JToggleButton();
        D8 = new javax.swing.JToggleButton();
        D9 = new javax.swing.JToggleButton();
        D10 = new javax.swing.JToggleButton();
        E1 = new javax.swing.JToggleButton();
        E2 = new javax.swing.JToggleButton();
        E3 = new javax.swing.JToggleButton();
        E4 = new javax.swing.JToggleButton();
        E5 = new javax.swing.JToggleButton();
        E6 = new javax.swing.JToggleButton();
        E7 = new javax.swing.JToggleButton();
        E8 = new javax.swing.JToggleButton();
        E9 = new javax.swing.JToggleButton();
        E10 = new javax.swing.JToggleButton();
        F1 = new javax.swing.JToggleButton();
        F2 = new javax.swing.JToggleButton();
        F3 = new javax.swing.JToggleButton();
        F4 = new javax.swing.JToggleButton();
        F5 = new javax.swing.JToggleButton();
        F6 = new javax.swing.JToggleButton();
        F7 = new javax.swing.JToggleButton();
        F8 = new javax.swing.JToggleButton();
        F9 = new javax.swing.JToggleButton();
        F10 = new javax.swing.JToggleButton();
        rbtnGeneral = new javax.swing.JRadioButton();
        rbtnPreferencial = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        docs = new javax.swing.JLabel();
        cod = new javax.swing.JTextField();
        error1 = new javax.swing.JLabel();
        error2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        error3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuClose = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(34, 140, 85));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Pantalla");
        jLabel4.setToolTipText("");
        jLabel4.setOpaque(true);
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 650, 23));

        A1.setBackground(new java.awt.Color(102, 255, 102));
        A1.setText("A1");
        A1.setOpaque(true);
        jPanel4.add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 50, 33));

        A2.setBackground(new java.awt.Color(102, 255, 102));
        A2.setText("A2");
        A2.setOpaque(true);
        jPanel4.add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 50, 33));

        A3.setBackground(new java.awt.Color(102, 255, 102));
        A3.setText("A3");
        A3.setOpaque(true);
        jPanel4.add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 50, 33));

        A4.setBackground(new java.awt.Color(102, 255, 102));
        A4.setText("A4");
        A4.setOpaque(true);
        jPanel4.add(A4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 50, 33));

        A5.setBackground(new java.awt.Color(102, 255, 102));
        A5.setText("A5");
        A5.setOpaque(true);
        jPanel4.add(A5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, 33));

        A6.setBackground(new java.awt.Color(102, 255, 102));
        A6.setText("A6");
        A6.setOpaque(true);
        jPanel4.add(A6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 50, 33));

        A7.setBackground(new java.awt.Color(102, 255, 102));
        A7.setText("A7");
        A7.setOpaque(true);
        jPanel4.add(A7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 50, 33));

        A8.setBackground(new java.awt.Color(102, 255, 102));
        A8.setText("A8");
        A8.setOpaque(true);
        jPanel4.add(A8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 50, 33));

        A9.setBackground(new java.awt.Color(102, 255, 102));
        A9.setText("A9");
        A9.setOpaque(true);
        jPanel4.add(A9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 50, 33));

        A10.setBackground(new java.awt.Color(102, 255, 102));
        A10.setText("A10");
        A10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        A10.setOpaque(true);
        jPanel4.add(A10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, -1, 33));

        B1.setBackground(new java.awt.Color(102, 255, 102));
        B1.setText("B1");
        B1.setOpaque(true);
        jPanel4.add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 50, 33));

        B2.setBackground(new java.awt.Color(102, 255, 102));
        B2.setText("B2");
        B2.setOpaque(true);
        jPanel4.add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 50, 33));

        B3.setBackground(new java.awt.Color(102, 255, 102));
        B3.setText("B3");
        B3.setOpaque(true);
        jPanel4.add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 50, 33));

        B4.setBackground(new java.awt.Color(102, 255, 102));
        B4.setText("B4");
        B4.setOpaque(true);
        jPanel4.add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 50, 33));

        B5.setBackground(new java.awt.Color(102, 255, 102));
        B5.setText("B5");
        B5.setOpaque(true);
        jPanel4.add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 50, 33));

        B6.setBackground(new java.awt.Color(102, 255, 102));
        B6.setText("B6");
        B6.setOpaque(true);
        jPanel4.add(B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 50, 33));

        B7.setBackground(new java.awt.Color(102, 255, 102));
        B7.setText("B7");
        B7.setOpaque(true);
        jPanel4.add(B7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 50, 33));

        B8.setBackground(new java.awt.Color(102, 255, 102));
        B8.setText("B8");
        B8.setOpaque(true);
        jPanel4.add(B8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 50, 33));

        B9.setBackground(new java.awt.Color(102, 255, 102));
        B9.setText("B9");
        B9.setOpaque(true);
        jPanel4.add(B9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 50, 33));

        B10.setBackground(new java.awt.Color(102, 255, 102));
        B10.setText("B10");
        B10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B10.setOpaque(true);
        jPanel4.add(B10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, -1, 33));

        C1.setBackground(new java.awt.Color(102, 255, 102));
        C1.setText("C1");
        C1.setOpaque(true);
        jPanel4.add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 50, 33));

        C2.setBackground(new java.awt.Color(102, 255, 102));
        C2.setText("C2");
        C2.setOpaque(true);
        jPanel4.add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 50, 33));

        C3.setBackground(new java.awt.Color(102, 255, 102));
        C3.setText("C3");
        C3.setOpaque(true);
        jPanel4.add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 50, 33));

        C4.setBackground(new java.awt.Color(102, 255, 102));
        C4.setText("C4");
        C4.setOpaque(true);
        jPanel4.add(C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 50, 33));

        C5.setBackground(new java.awt.Color(102, 255, 102));
        C5.setText("C5");
        C5.setOpaque(true);
        jPanel4.add(C5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 50, 33));

        C6.setBackground(new java.awt.Color(102, 255, 102));
        C6.setText("C6");
        C6.setOpaque(true);
        jPanel4.add(C6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 50, 33));

        C7.setBackground(new java.awt.Color(102, 255, 102));
        C7.setText("C7");
        C7.setOpaque(true);
        jPanel4.add(C7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 50, 33));

        C8.setBackground(new java.awt.Color(102, 255, 102));
        C8.setText("C8");
        C8.setOpaque(true);
        jPanel4.add(C8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 50, 33));

        C9.setBackground(new java.awt.Color(102, 255, 102));
        C9.setText("C9");
        C9.setOpaque(true);
        jPanel4.add(C9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 50, 33));

        C10.setBackground(new java.awt.Color(102, 255, 102));
        C10.setText("C10");
        C10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        C10.setOpaque(true);
        jPanel4.add(C10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, -1, 33));

        D1.setBackground(new java.awt.Color(102, 255, 102));
        D1.setText("D1");
        D1.setOpaque(true);
        jPanel4.add(D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, 33));

        D2.setBackground(new java.awt.Color(102, 255, 102));
        D2.setText("D2");
        D2.setOpaque(true);
        jPanel4.add(D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 50, 33));

        D3.setBackground(new java.awt.Color(102, 255, 102));
        D3.setText("D3");
        D3.setOpaque(true);
        jPanel4.add(D3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 50, 33));

        D4.setBackground(new java.awt.Color(102, 255, 102));
        D4.setText("D4");
        D4.setOpaque(true);
        jPanel4.add(D4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 50, 33));

        D5.setBackground(new java.awt.Color(102, 255, 102));
        D5.setText("D5");
        D5.setOpaque(true);
        jPanel4.add(D5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 50, 33));

        D6.setBackground(new java.awt.Color(102, 255, 102));
        D6.setText("D6");
        D6.setOpaque(true);
        jPanel4.add(D6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 50, 33));

        D7.setBackground(new java.awt.Color(102, 255, 102));
        D7.setText("D7");
        D7.setOpaque(true);
        jPanel4.add(D7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 50, 33));

        D8.setBackground(new java.awt.Color(102, 255, 102));
        D8.setText("D8");
        D8.setOpaque(true);
        jPanel4.add(D8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 50, 33));

        D9.setBackground(new java.awt.Color(102, 255, 102));
        D9.setText("D9");
        D9.setOpaque(true);
        jPanel4.add(D9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 50, 33));

        D10.setBackground(new java.awt.Color(102, 255, 102));
        D10.setText("D10");
        D10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        D10.setOpaque(true);
        jPanel4.add(D10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, -1, 33));

        E1.setBackground(new java.awt.Color(102, 255, 102));
        E1.setText("E1");
        jPanel4.add(E1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 50, 33));

        E2.setBackground(new java.awt.Color(102, 255, 102));
        E2.setText("E2");
        jPanel4.add(E2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 50, 33));

        E3.setBackground(new java.awt.Color(102, 255, 102));
        E3.setText("E3");
        jPanel4.add(E3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 50, 33));

        E4.setBackground(new java.awt.Color(102, 255, 102));
        E4.setText("E4");
        jPanel4.add(E4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 50, 33));

        E5.setBackground(new java.awt.Color(102, 255, 102));
        E5.setText("E5");
        jPanel4.add(E5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 50, 33));

        E6.setBackground(new java.awt.Color(102, 255, 102));
        E6.setText("E6");
        jPanel4.add(E6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 50, 33));

        E7.setBackground(new java.awt.Color(102, 255, 102));
        E7.setText("E7");
        jPanel4.add(E7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 50, 33));

        E8.setBackground(new java.awt.Color(102, 255, 102));
        E8.setText("E8");
        jPanel4.add(E8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 50, 33));

        E9.setBackground(new java.awt.Color(102, 255, 102));
        E9.setText("E9");
        jPanel4.add(E9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 50, 33));

        E10.setBackground(new java.awt.Color(102, 255, 102));
        E10.setText("E10");
        E10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel4.add(E10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, -1, 33));

        F1.setBackground(new java.awt.Color(102, 255, 102));
        F1.setText("F1");
        jPanel4.add(F1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 50, 33));

        F2.setBackground(new java.awt.Color(102, 255, 102));
        F2.setText("F2");
        jPanel4.add(F2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 50, 33));

        F3.setBackground(new java.awt.Color(102, 255, 102));
        F3.setText("F3");
        jPanel4.add(F3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 50, 33));

        F4.setBackground(new java.awt.Color(102, 255, 102));
        F4.setText("F4");
        jPanel4.add(F4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 50, 33));

        F5.setBackground(new java.awt.Color(102, 255, 102));
        F5.setText("F5");
        jPanel4.add(F5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 50, 33));

        F6.setBackground(new java.awt.Color(102, 255, 102));
        F6.setText("F6");
        jPanel4.add(F6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 50, 33));

        F7.setBackground(new java.awt.Color(102, 255, 102));
        F7.setText("F7");
        jPanel4.add(F7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 50, 33));

        F8.setBackground(new java.awt.Color(102, 255, 102));
        F8.setText("F8");
        jPanel4.add(F8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 50, 33));

        F9.setBackground(new java.awt.Color(102, 255, 102));
        F9.setText("F9");
        jPanel4.add(F9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 50, 33));

        F10.setBackground(new java.awt.Color(102, 255, 102));
        F10.setText("F10");
        F10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel4.add(F10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, -1, 33));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 138, 690, 340));

        rbtnGeneral.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbtnGeneral.setText("General ($11.000)");
        rbtnGeneral.setOpaque(false);
        rbtnGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnGeneralActionPerformed(evt);
            }
        });
        jPanel3.add(rbtnGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        rbtnPreferencial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbtnPreferencial.setText("Preferencial ($15.000)");
        rbtnPreferencial.setOpaque(false);
        rbtnPreferencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPreferencialActionPerformed(evt);
            }
        });
        jPanel3.add(rbtnPreferencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1400, 70, 20));

        jButton1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jButton1.setText("Confirmar compra");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 490, 150, 40));

        error.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        error.setText("Seleccione al menos un asiento");
        jPanel3.add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, 290, -1));

        docs.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        docs.setText("Documento del usuario");
        jPanel3.add(docs, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 460, 150, -1));

        cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codActionPerformed(evt);
            }
        });
        jPanel3.add(cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, 90, 30));

        error1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        error1.setText("El documento no se encuentra registrado");
        jPanel3.add(error1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 570, 260, 40));

        error2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        error2.setText("Seleccione al menos un asiento");
        jPanel3.add(error2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, 290, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo5.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1040, -1));

        error3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        error3.setText("Seleccione al menos un asiento");
        jPanel3.add(error3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 290, -1));

        jLabel1.setText("jLabel1");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        jMenu1.setText("Ajustes");

        menuClose.setText("Cerrar Sesión");
        menuClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCloseActionPerformed(evt);
            }
        });
        jMenu1.add(menuClose);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void menuCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.cntl.setEmpleado(null);
        this.cntl.setPer(null);
        cntl.newPeli();
    }//GEN-LAST:event_menuCloseActionPerformed

    private void codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean select=false;
        for (int i = 0; i < 2; i++) {
            for (int j = 0; j < 10; j++) {
                if(sillasPref[i][j].isSelected()){
                    this.cntl.addSilla(i+4, j);
                    select=true;
                }

            }
        }

        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 10; j++) {
                if(this.sillasGener[i][j].isSelected()){
                    this.cntl.addSilla(i, j);
                    select=true;
                }
            }
        }
        if(select){
            this.dispose();
            this.cntl.setFinal();
        }else{
            this.error.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rbtnPreferencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPreferencialActionPerformed

        for (int i = 0; i < 2; i++) {
            for (int j = 0; j < 10; j++) {
                if(this.rbtnPreferencial.isSelected()){
                    this.sillasPref[i][j].setEnabled(cntl.getEstado(i+4,j));
                }else{
                    this.sillasPref[i][j].setEnabled(false);
                    this.sillasPref[i][j].setSelected(false);
                }

            }
        }

    }//GEN-LAST:event_rbtnPreferencialActionPerformed

    private void rbtnGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnGeneralActionPerformed
        //Al presionar el boton de silla general se desactivan los botones de silla preferencial

        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 10; j++) {
                if(this.rbtnGeneral.isSelected()){
                    this.sillasGener[i][j].setEnabled(cntl.getEstado(i,j));
                }else{
                    this.sillasGener[i][j].setEnabled(false);
                    this.sillasGener[i][j].setSelected(false);
                }
            }
        }
    }//GEN-LAST:event_rbtnGeneralActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton A1;
    private javax.swing.JToggleButton A10;
    private javax.swing.JToggleButton A2;
    private javax.swing.JToggleButton A3;
    private javax.swing.JToggleButton A4;
    private javax.swing.JToggleButton A5;
    private javax.swing.JToggleButton A6;
    private javax.swing.JToggleButton A7;
    private javax.swing.JToggleButton A8;
    private javax.swing.JToggleButton A9;
    private javax.swing.JToggleButton B1;
    private javax.swing.JToggleButton B10;
    private javax.swing.JToggleButton B2;
    private javax.swing.JToggleButton B3;
    private javax.swing.JToggleButton B4;
    private javax.swing.JToggleButton B5;
    private javax.swing.JToggleButton B6;
    private javax.swing.JToggleButton B7;
    private javax.swing.JToggleButton B8;
    private javax.swing.JToggleButton B9;
    private javax.swing.JToggleButton C1;
    private javax.swing.JToggleButton C10;
    private javax.swing.JToggleButton C2;
    private javax.swing.JToggleButton C3;
    private javax.swing.JToggleButton C4;
    private javax.swing.JToggleButton C5;
    private javax.swing.JToggleButton C6;
    private javax.swing.JToggleButton C7;
    private javax.swing.JToggleButton C8;
    private javax.swing.JToggleButton C9;
    private javax.swing.JToggleButton D1;
    private javax.swing.JToggleButton D10;
    private javax.swing.JToggleButton D2;
    private javax.swing.JToggleButton D3;
    private javax.swing.JToggleButton D4;
    private javax.swing.JToggleButton D5;
    private javax.swing.JToggleButton D6;
    private javax.swing.JToggleButton D7;
    private javax.swing.JToggleButton D8;
    private javax.swing.JToggleButton D9;
    private javax.swing.JToggleButton E1;
    private javax.swing.JToggleButton E10;
    private javax.swing.JToggleButton E2;
    private javax.swing.JToggleButton E3;
    private javax.swing.JToggleButton E4;
    private javax.swing.JToggleButton E5;
    private javax.swing.JToggleButton E6;
    private javax.swing.JToggleButton E7;
    private javax.swing.JToggleButton E8;
    private javax.swing.JToggleButton E9;
    private javax.swing.JToggleButton F1;
    private javax.swing.JToggleButton F10;
    private javax.swing.JToggleButton F2;
    private javax.swing.JToggleButton F3;
    private javax.swing.JToggleButton F4;
    private javax.swing.JToggleButton F5;
    private javax.swing.JToggleButton F6;
    private javax.swing.JToggleButton F7;
    private javax.swing.JToggleButton F8;
    private javax.swing.JToggleButton F9;
    private javax.swing.ButtonGroup btnGrupo;
    private javax.swing.JTextField cod;
    private javax.swing.JLabel docs;
    private javax.swing.JLabel error;
    private javax.swing.JLabel error1;
    private javax.swing.JLabel error2;
    private javax.swing.JLabel error3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JMenuItem menuClose;
    private javax.swing.JRadioButton rbtnGeneral;
    private javax.swing.JRadioButton rbtnPreferencial;
    // End of variables declaration//GEN-END:variables
}
